### ISSUE TITLE
BUG Invalid PDF of candidate in LG22

### ISSUE THREAD

**Issue by jovan-stojanovic** [regardscitoyens/professions-foi-candidats-2021#1]
Hello,

Thanks for the great scraping work!

I see the PDF file of the profession de foi is "invalid" for the candidates:
- [Lynda MEGUENINE in LG22](https://github.com/regardscitoyens/professions-foi-candidats-2021/blob/main/documents/LG22/51/02/LG22-51-02-tour1-9-Lynda%20MEGUENINE-profession_foi.pdf).
- [Céline CELCE in LG22](https://github.com/regardscitoyens/professions-foi-candidats-2021/blob/main/documents/LG22/84/05/LG22-84-05-tour1-2-C%C3%A9line%20CELCE-profession_foi.pdf).

I can also see that the correct PDF is easily downloadable from the official website:
- For [Lynda MEGUENINE](https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/candidats.html?circo=02&departement=51&tour=1).
- For [Céline CELCE](https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/candidats.html?circo=05&departement=84&tour=1).

I can create a quick fix PR and replace the pdf if you want, let me know.

**Comment by boogheta** [comment]
Hi and thanks for the report, I'll gladly accept a PR, thanks!
